name: Acciojob Tests

on:
  push:
    branches: [ "main","master" ]

jobs:
  checking-question-type:
    runs-on: ubuntu-latest
    steps:
    - name: Running main workflow
      uses: acciojob/acciojob-tests-action@latest
      
