name: Java CI with Maven

on:
  push:
    branches: [ "main","master" ]

jobs:
  checking-question-type:
    runs-on: ubuntu-latest
    steps:
    - name: Checking Question Type
      id: checkingQuestionType
      uses: acciojob/checking-question-type-action@v0.4
      env:  
        ACCIO_ASGMNT_ACTION_TOKEN: ${{ secrets.ACCIO_ASGMNT_ACTION_TOKEN }}
        ACCIOJOB_BACKEND_URL: ${{ vars.ACCIOJOB_BACKEND_URL }}
    outputs: 
      questionType: ${{ steps.checkingQuestionType.outputs.questionType }}

  running-accio-cypress-tests:
    runs-on: ubuntu-latest
    needs: checking-question-type 
    if: needs.checking-question-type.outputs.questionType == 'REACT'
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Acciojob Assignment Action
        id: assignmentAction
        uses: acciojob/assignment-action@v0.0.2
        env:
          ACCIO_ASGMNT_ACTION_TOKEN: ${{ secrets.ACCIO_ASGMNT_ACTION_TOKEN }}
          ACCIOJOB_BACKEND_URL: ${{ vars.ACCIOJOB_BACKEND_URL }}
      - run: echo "üçè Score - ${{ steps.assignmentAction.outputs.scoreReceived }}/${{ steps.assignmentAction.outputs.totalScore }}"

  
  running-accio-junit-tests:
    runs-on: ubuntu-latest
    needs: checking-question-type 
    if: needs.checking-question-type.outputs.questionType == 'JAVA'
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Junit Assignment Action
      id: assignmentAction
      uses: acciojob/junit-github-action@v0.12
      env:
          ACCIO_ASGMNT_ACTION_TOKEN: ${{ secrets.ACCIO_ASGMNT_ACTION_TOKEN }}
          ACCIOJOB_BACKEND_URL: ${{ vars.ACCIOJOB_BACKEND_URL }}

  


